### ISSUE TITLE
This XML file does not appear to have any style information associated with it

### ISSUE THREAD

**Issue by ajaylg** [SchabanBo/qlevar_router#10]
I used the url_strategy flutter package to remove /#/ from the web URL and define routes for pages as per your package example
and hosted to AWS S3 it's working fine as per your Solution in #9  but when I refresh the URL from any page it shows access denied
![Capture](https://user-images.githubusercontent.com/42292816/112256380-b4ffc000-8c89-11eb-8681-ec99c14225ed.PNG)

**Comment by SchabanBo** [comment]
Hi @ajaylg 
This is not something from the package. you need to configure your server to redirect all unknown pages to `index.html` so flutter can handle the URL.
to do so you need to create a `.htaccess` file in the same folder where you `index.html` file is and add the flowing in it:
```
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
```
BTW: you can remove the hashtag from the URL using. It is not in the dous yet.
```dart
void main() {
  QR.setUrlStrategy();
  runApp(MyApp());
}
```

**Comment by ajaylg** [comment]
I created .htaccess file and imported the above code you provided but nothing happens shows same result as mentioned above 
#10

**Comment by ajaylg** [comment]
Can you Provide Some Detail information about this hosting
@SchabanBo

**Comment by SchabanBo** [comment]
@ajaylg 
unfortunately, I don't know, I didn't use S3 before.
I tried this method [here](https://routerexample.qlevar.de) and it seems, it works fine

**Comment by guruprakashIT** [comment]
Hi @SchabanBo 

when i deploy build file in netlify . it works all routings are works, once i refresh the page. it gives the 404 page not found!

can you please help me out from this issue

**Comment by SchabanBo** [comment]
Hi @guruprakashIT ,
As I know the redirect in netlify is a little bit different. See [here](https://docs.netlify.com/routing/redirects/)
I didn't try it. but you need to redirect all the requests to the `index.html` file

**Comment by ajaylg** [comment]
I solved

> Hi @SchabanBo
> 
> when i deploy build file in netlify . it works all routings are works, once i refresh the page. it gives the 404 page not found!
> 
> can you please help me out from this issue


I Solved this issue in AWS S3 Static web hosting by simply adding index.html in error document field like this
@guruprakashIT 
@SchabanBo 
![Capture](https://user-images.githubusercontent.com/42292816/114134247-0912d180-9925-11eb-8205-30255c08b420.PNG)

**Comment by ajaylg** [comment]
I don't no this is the right solution, but it works in my case
@guruprakashIT
