### ISSUE TITLE
when we using bottom Sheet and alert dialog it can't pop out the dialog

### ISSUE THREAD

**Issue by anandrajak2** [SchabanBo/qlevar_router#101]

**Comment by SchabanBo** [comment]
Hi @anandrajak2,
What can not pop out, could you add an example?

**Comment by SchabanBo** [comment]
Hi @westlinkin,
Thanks for your feedback, I have found the problem and working on it

**Comment by westlinkin** [comment]
@SchabanBo 

Thanks. I found a workaround, [back_button_interceptor](https://pub.dev/packages/back_button_interceptor) is needed. In every screen, check if a ModalRoute is active, if so, pops that ModalRoute and consumes the back button event; if not, do not do anything.

`ModalRoute.of(context)?.isCurrent != true` means a ModalRoute is presented (need to intercept the back button event)

**Comment by SchabanBo** [comment]
Exactly @westlinkin, that was the problem. When you add a buttom_sheet, this is done with `Navigator.push`. In this case, qlevar_router does not know that there is something else that should be removed and removes the last route. So I am trying to add a way for qlevar_router to check first if there are any other routes added from outside the package.
But it is good that you have found something to fix it now.
