### ISSUE TITLE
Nested route with the same name/path

### ISSUE THREAD

**Issue by michaelprimez** [SchabanBo/qlevar_router#103]
Hi,
I have the below setup in my app:

```
...
children: [
  QRoute.withChild(
     name: 'events',
     path: '/events',
     initRoute: '/list',
     builderChild: (r) => r,
     children: [
         QRoute(
           name: 'list',
           path: '/list',
           builder: () => const LocationsEditorGridScreen<Event>()
         ),
         QRoute(
           name: 'find',
           path: '/find',
           builder: () => const FindLocationScreen<Event>()
         ),
     ]
  ),
  QRoute.withChild(
     name: 'places',
     path: '/places',
     initRoute: '/list',
     builderChild: (r) => r,
     children: [
         QRoute(
           name: 'list',
           path: '/list',
           builder: () => const LocationsEditorGridScreen<Place>()
         ),
         QRoute(
           name: 'find',
           path: '/find',
           builder: () => const FindLocationScreen<Place>()
         ),
     ]
  )
]
```
The problem seams to be the same name of the children routes, even thought are nested routes. When, for example, I perform QR.toName('find') from inside '/events' it opens the /find of the /places. 
More specific, when the the route is `/events/list` and I perform `QR.toName('find')` it opens the `/places/find`. Another clue is that if I reverse the routes 
```
QRoute.withChild(
     name: 'places',
     ...
QRoute.withChild(
     name: 'events',
     ...
```
and I place the `events` route last, then :
when is `/places/list` and I am trying to navigate to `QR.toName('find')` it opens the `/events/find`.
Seams that always the last defined is selected.

Thanks
Michael

**Comment by SchabanBo** [comment]
HI @michaelprimez,
The route name should always be unique. So if new route is defined with a name already has been defined. The new route will replace the old one. That is why you are getting the second one.
II I am thinking now, n this case the package should throw an error not replacing the route. This will confuse the developers. I will change this.
So to fix this, all you need to do is choosing a unique name for each route.

**Comment by michaelprimez** [comment]
Hi @SchabanBo ,

Thank you for your reply. 
I understand your sayings and are in align with the behavior that I am facing, but I believe that `/events/find` and the `places/find` shouldn't have any conflict and nested routes should not conflict even if another nested route has the same name.
Also, I believe, if you allow nested route to have the same name it will improve the already high quality of the library :).

Thanks

**Comment by SchabanBo** [comment]
Not exactly, because we should consider any navigation case, one of them the case that the user wants to navigate from `events/find` to `places/find`.

**Comment by michaelprimez** [comment]
Usually, the users navigate to main list/grid first for example `/events` and then to `/events/find`. But  even if a user navigates from `/events/find` directly to `/places/find`, I can see any problem with this case. Can you please explain why this case is problematic?

**Comment by SchabanBo** [comment]
The route name here is working like an ID for the routes, and they are saved in [a map](https://github.com/SchabanBo/qlevar_router/blob/master/lib/src/qr.dart#L358).

So when you call QR.toName the package is looking for the route path with this name in the map and then navigate to it. That is why it could be a problem saving more than one route with the same name.
