### ISSUE TITLE
Auto redirected to not found page

### ISSUE THREAD

**Issue by Jens05** [SchabanBo/qlevar_router#104]
When i have built my website and i change my route in the url i get redirected to a not found page.

Example:
My domain is test.com and when i tap a button i get to test.com/newpage. But when i type this url directly into my browser i get to url not found. 

Any help is appreciated :)

**Comment by Jens05** [comment]
After futher investigation i found out that this happens when i set a url strategy. Please fix this :)

**Comment by SchabanBo** [comment]
Hi @Jens05,
Did you try [this](https://github.com/SchabanBo/qlevar_router/issues/10#issuecomment-805905670)?
