### ISSUE TITLE
A QRouterController was used after being disposed.

### ISSUE THREAD

**Issue by Krishnachand07** [SchabanBo/qlevar_router#11]

**Comment by Krishnachand07** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/53311684/112257784-5f2c1780-8c8b-11eb-9c97-c6b3fc2eecfe.png)

While restoring the window to tab mode and again maximize to desktop, it shows a error like this

**Comment by SchabanBo** [comment]
Hello @Krishnachand07 , Thank you for opening the issue. Unfortunately, I could not reproduce the problem.
Could you enable the debug log in the package with
```dart
 QR.settings.enableDebugLog = true;
```
and show me the logs when the problem is happing?

**Comment by Krishnachand07** [comment]
> Hello @Krishnachand07 , Thank you for opening the issue. Unfortunately, I could not reproduce the problem.
> Could you enable the debug log in the package with
> 
> ```dart
>  QR.settings.enableDebugLog = true;
> ```
> 
> and show me the logs when the problem is happing?

**Comment by Krishnachand07** [comment]
I used responsive layout for mobile, tab, and desktop
![image](https://user-images.githubusercontent.com/53311684/112595316-427d1480-8e30-11eb-949b-c6724f842166.png)
in-browser I shrink the page desktop to tab, routing works well. but when I maximize the screen from tab to desktop this error occurs
![image](https://user-images.githubusercontent.com/53311684/112595005-cf739e00-8e2f-11eb-97fd-2ae8edb339c3.png)

**Comment by SchabanBo** [comment]
Issue found.
I fixed it with version 1.1.1
Thank you for pointing to it.
