### ISSUE TITLE
Path '/' not working with QRoute.withChild

### ISSUE THREAD

**Issue by doublegarts** [SchabanBo/qlevar_router#111]
Consider the next scenario:

```dart
final routes = [
  QRoute.withChild(
    path: '/',
    name: home,
    initRoute: '/about',
    builderChild: (router) => HomeScreen(router: router),
    children: [
      QRoute(
        path: '/about',
        name: about,
        builder: () => const AboutScreen(),
      ),
      QRoute(
        path: '/contact',
        name: contact,
        builder: () => const ContactScreen(),
      ),
    ],
  ),
];
```

It loads the AboutScreen inside the HomeScreen, but the path is missing from url. Also, when you try to switch to the ContactsScreen it navigates to the error page, the path still missing from the url.

If I change the path from '/' to '/home' or something else, it works properly, but I do not want to have 'home' inside the path.

**Comment by carlosfiori** [comment]
Hi @doublegarts, 

Try this workaround, it works for me:
Add `initPath` on MaterialApp.router to '/about'
and update `QRoute.withChild` path to '/about' and change first route to `/`

Something like this:

```dart
final routes = [
  QRoute.withChild(
    path: '/about',
    name: home,
    builderChild: (router) => HomeScreen(router: router),
    children: [
      QRoute(
        path: '/',
        name: about,
        builder: () => const AboutScreen(),
      ),
      QRoute(
        path: '/contact',
        name: contact,
        builder: () => const ContactScreen(),
      ),
    ],
  ),
];
```

```dart
MaterialApp.router(
      routeInformationParser: const QRouteInformationParser(),
      routerDelegate: QRouterDelegate(
        AppRoutes().routes,
        initPath: '/about',
      ),
    );
```

**Comment by SchabanBo** [comment]
Yes, that was a problem since a long time now. But I have not had the time for it. And the workaround for it was as @carlosfiori mentioned. I fixed this in develop branch and will be out in the next release. The test for this is [here](https://github.com/SchabanBo/qlevar_router/blob/develop/test/scenario-code/issue_111_test.dart)
