### ISSUE TITLE
Error using Nested Routes & setUrlStrategy

### ISSUE THREAD

**Issue by guilherme-diniz** [SchabanBo/qlevar_router#114]
If I set the UrlStrategy (using `QR.setUrlStrategy`) and create a Nested Navigator, when I refresh the page I get a blank screen. If I remove the `setUrlStrategy`, everything works out.

### With setUrlStrategy
![Captura de Tela 2023-03-06 às 19 33 59](https://user-images.githubusercontent.com/64857365/223264532-fe19e2b8-dcda-484d-8d4f-3acc7f1412a0.png)

### Without setUrlStrategy
![Captura de Tela 2023-03-06 às 19 35 18](https://user-images.githubusercontent.com/64857365/223265286-dc470214-ef98-4fdc-a3c3-b8de147d5e8f.png)

**Comment by SchabanBo** [comment]
Actually, it is a limitation from the browser and not a Problem from the package. 
[See this](https://github.com/flutter/flutter/issues/121063#issuecomment-1436943745) Here the same thing is happening when you reload the page, without the hashtag, you are requesting the file in the path /home/coffee, which doesn't exist.
As you see here, the browser is requesting the /home/main.dart.js 
![image](https://user-images.githubusercontent.com/49782771/223963163-c7e5c3b9-ae72-40d5-b2b8-0c4147925e9d.png)

**Comment by devhammed** [comment]
@guilherme-diniz The solution is to make all unknown requests go to the index.html file (just like the setup in SPA sites).

Below are sample configurations for Apache & Nginx servers:

Apache:

	<VirtualHost *:80>
		ServerName mydomainname.in
		DirectoryIndex index.html
		DocumentRoot /var/www/html
	
		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined
	
		<Location / >
			RewriteEngine on
			RewriteCond %{REQUEST_FILENAME} !-d
			RewriteCond %{REQUEST_FILENAME} !-f
			RewriteRule . /index.html [L]
		</Location>
	</VirtualHost>

Nginx:

	server {
	    server_name mydomainname.in;
	    index index.html;
	    error_log  /var/log/nginx/error.log;
	    access_log /var/log/nginx/access.log;
	    root /usr/share/nginx/html;
	  
	    location / {
	        try_files $uri $uri/ /index.html;
	    }
	}
