### ISSUE TITLE
MacOS Top Web Bar is Empty

### ISSUE THREAD

**Issue by doublegarts** [SchabanBo/qlevar_router#117]
When I set withWebBar to true I can see the web bar on the top of the screen but the path is empty at start.
If I navigate to a screen then go back it appears.
Also, there is no way to deactivate debugBanner inside it.

I have this issues on a MacBook Pro M1, never tested on other desktop platforms such as Windows or Linux.

**Comment by SchabanBo** [comment]
I forget to set the controller text at the start. I fixed this and will be out in the next version.
Thanks for noticing.
