### ISSUE TITLE
Changing Middleware Name?

### ISSUE THREAD

**Issue by SchabanBo** [SchabanBo/qlevar_router#118]
Hi everyone,

I'm considering a potential name change for the `Middleware` feature in the package to `Interceptor` or another more suitable term. The term `Middleware` may not fully describe the functionality of the feature, and it deviates from the traditional middleware design where the next function is typically called.

I would love to hear your thoughts on this proposed change. Do you agree that the current name is not entirely accurate? Would you prefer the new name `Interceptor`, or do you have any other suggestions for a more suitable name that accurately reflects the function of this feature?

Thank you for your time and support.

**Comment by devhammed** [comment]
@SchabanBo What do you think of RouteGuard?
