### ISSUE TITLE
Strange "Loading" text on the background

### ISSUE THREAD

**Issue by doublegarts** [SchabanBo/qlevar_router#119]
There is a white screen with "Loading" text centered. It appears when I start the app or when I hot restart.
I would like to be able to remove it or change it.

**Comment by doublegarts** [comment]
A screenshot finally captured:

<img width="557" alt="Screenshot 2023-03-14 at 23 30 09" src="https://user-images.githubusercontent.com/78120296/225141567-b808d420-b842-4eb2-969a-a58ec3bcf494.png">

**Comment by SchabanBo** [comment]
This is the [initPage](https://github.com/SchabanBo/qlevar_router/blob/8ef42a1d9100e602140200ae83bf520d3c60a218/lib/src/qr.dart#L354). This page is the default page to show when the app starts until the first route is loaded. to change it you can do
```dart
QR.settings.initPage = YourPage();
```
