### ISSUE TITLE
Dashbord with Sidebar and AppBar

### ISSUE THREAD

**Issue by Gino1963** [SchabanBo/qlevar_router#128]
Hi, thanks for this great qlevar_router.
I would like to have an example to handle this scenario.

I have a Dashboard with a left Sidebar and an Appbar

![Immagine 2023-04-27 193413](https://user-images.githubusercontent.com/21334010/234943475-eed0ee4e-9b41-4c47-a9cc-6aa2bb91d593.png)

By selecting an item in the sidebar, I open a page and simultaneously add a button in the AppBar

![Immagine 2023-04-27 193708](https://user-images.githubusercontent.com/21334010/234944062-639f1494-2559-4f1a-8078-79ea9c1347dc.png)

After opening several pages I would like to jump from one page to another using only the Appbar, keeping the status of each page.
I can't configure qlevar correctly to solve my scenario. Anyone have suggestions?

Thanks

Biagio

**Comment by Gino1963** [comment]
I'm sorry for my english !!!!

**Comment by SchabanBo** [comment]
Hi @Gino1963 ,
To save the state of the page, you can see [this](https://github.com/flutter/packages/blob/d041934b296d1a359f0be632983318562d447998/packages/go_router/lib/src/misc/extensions.dart#L24)
