### ISSUE TITLE
Path '/' not working with QRoute.withChild, when using QR.toName

### ISSUE THREAD

**Issue by k-ane** [SchabanBo/qlevar_router#129]
This is a follow up to this issue: https://github.com/SchabanBo/qlevar_router/issues/111

When navigating using the QR.to(path) syntax, everything works as expected. However when using names instead of paths (QR.toName), the routing breaks.

You can verify this by changing the provided test to use QR.toName instead of QR.to: https://github.com/SchabanBo/qlevar_router/blob/develop/test/scenario-code/issue_111_test.dart

**Comment by ElectraPort** [comment]
Can confirm these fixes are good, have now moved to the repo by path that has them in it. I've been thinking for almost a year this was me not understanding how the router worked :) Cost me months but this now works exactly as I expected. @SchabanBo please merge ASAP so we don't have to use this fork. Thanks!

**Comment by SchabanBo** [comment]
@k-ane can you open PR?
