### ISSUE TITLE
Add a way to await for route pushes

### ISSUE THREAD

**Issue by Zazo032** [SchabanBo/qlevar_router#133]
With other navigation plugins, like `go_router`, you can do something like this:
```dart
onTap: () async {
  await context.go('/profile');
  callback();
}
```

Here, the `callback()` function runs after you pop the `/profile` route.

However, a similar approach with `qlevar_router` doesn't seem to work:

```dart
onTap: () async {
  await QR.to('/profile');
  callback();
}
```

In this case, the `callback()` function runs after the new route is pushed, without waiting for a pop.

Is there any way to achieve a similar behaviour with this plugin?

**Comment by SchabanBo** [comment]
Hi @Zazo032 

As far as I know, waiting for a route with Nav2 is not currently possible. In the provided example, using the `context.go` method does not provide [ a future to wait for](https://github.com/flutter/packages/blob/d041934b296d1a359f0be632983318562d447998/packages/go_router/lib/src/misc/extensions.dart#L24).

Unfortunately, I don't have any specific resources or methods on how to achieve this behavior.
However, it would be a great feature to have, if you have any resource on how to do it, I would be happy to receive it.

In the meantime, you can consider alternative approaches to achieve similar behavior, such as using callbacks or custom event handling to trigger the desired actions after the route is complete.

**Comment by Zazo032** [comment]
@SchabanBo it's not available in the official plugin, but there's a workaround that might help here too: https://github.com/flutter/flutter/issues/108764#issuecomment-1367171796

**Comment by SchabanBo** [comment]
This is now in version 1.10.0 [More info](test\waiting_results_test.dart)
Thanks for feature request and the info on how to do it 😀
