### ISSUE TITLE
Can not rerender claver routing

### ISSUE THREAD

**Issue by wahyueko22** [SchabanBo/qlevar_router#137]
QRoute(
      path: "/",
      builder: () =>  def_dashboard.DashboardView(),
      middleware: [
        DefferedLoader(def_dashboard.loadLibrary),
      ],
    ),

can not rerender DashboardView for more than one calls, so my new value on page is not updated.

**Comment by SchabanBo** [comment]
I think you need to do `QR.to('path', ignoreSamePath: false)`
