### ISSUE TITLE
Add or remove routes in run Time

### ISSUE THREAD

**Issue by Gino1963** [SchabanBo/qlevar_router#139]
Hi.

I love add and remove routes !!!!!

I have a problem when I remove a route.

This is my stack tree:

![stack1](https://github.com/SchabanBo/qlevar_router/assets/21334010/37c0b054-1a73-4b24-98ff-7bc5c5a04e0e)

I add the route "products":

QR: Route: Key: [11](products), Full Path: /dashboard/products was add to Key: [2](/dashboard)
QR: Finding Match for /dashboard/products under root
QR: adding Route: Key: [11](products), Full Path: /dashboard/products to the navigator with Key: [9](/dashboard)

Now my stack tree is:
![stack2](https://github.com/SchabanBo/qlevar_router/assets/21334010/242e32c8-24b8-457b-a316-ae63492636e6)

If I remove de above route the debug message is:

QR: products is removed from Key: [2](/dashboard)

and the stack tree is correct.

If I try to add the same route again the error appears:

The following assertion was thrown while handling a gesture:
Assertion failed:
file:///C:/Users/Biagio/AppData/Local/Pub/Cache/hosted/pub.dev/qlevar_router-1.10.0/lib/src/routes/qroute_internal.dart:70:14
qroute_internal.dart:70
!QR.treeInfo.namePath.containsKey(route.name)
"Route name products (with path /dashboard/products) is already used by path /dashboard/products,
please use a unique name for each route."

But the route has been removed ... I don't understand !!!!

Thanks in advance

Biagio

**Comment by c-seeger** [comment]
can confirm this issue:

```
QR.rootNavigator.addRoutes(<QRoute>[
  QRoute(path: '/test', builder () => const TestPage())
]);
QR.rootNavigator.removeRoutes(<String>['/test']);

// throws an error Path /test already exist, cannot add
QR.rootNavigator.addRoutes(<QRoute>[
  QRoute(path: '/test', builder () => const TestPage())
]);
```
