### ISSUE TITLE
Crash in _BrowserAddressBarState

### ISSUE THREAD

**Issue by BarashkovaElena** [SchabanBo/qlevar_router#151]
_BrowserAddressBarState subscribes to listen to the controller, but doesn't remove listener when the widgets is destroyed. Because of that the code crashes after the widget is rebuilt whenever the current path changes.
Here is a fix suggestion for browser_address_bar.dart:
```
  void _listener() {
    setState(() {
      controller.text = QR.currentPath;
      if (_paths.isNotEmpty && QR.currentPath != _paths.last) {
        _paths.clear();
      }
    });
  }

  @override
  void initState() {
    super.initState();
    widget._controller.addListener(_listener);
  }

  @override
  void dispose() {
    widget._controller.removeListener(_listener);
    super.dispose();
  }
```

**Comment by SchabanBo** [comment]
Thanks for the fix suggestion. I have added it.
