### ISSUE TITLE
Add Bottom Sheet to AppRoutes

### ISSUE THREAD

**Issue by BarashkovaElena** [SchabanBo/qlevar_router#152]
Is there a way to add bottom sheet as a QRoute?
I need to have modal bottom sheet as a part of the current path, so that it is restored during app state restoration.
If bottom sheet is added via Navigator, it will not be restored, because qlevar router doesn't know about bottom sheet.

**Comment by miaosun009** [comment]
@BarashkovaElena 
Is this what you need? https://github.com/SchabanBo/qlevar_router/pull/155
