### ISSUE TITLE
[BUG] QR.replaceLast, page not disposed!

### ISSUE THREAD

**Issue by offline-first** [SchabanBo/qlevar_router#157]
Hey!
The method `QR.replaceLast('/new-route');` does not dispose of the current route with a StatefulWidget.
How can this be fixed?

**Comment by SchabanBo** [comment]
Can you provide an Example code?

**Comment by offline-first** [comment]
Sorry for the late answer.

The QR.replaceLast('/new-path') function is not correctly replacing the current route on Android devices. When navigating back, the replaced route is still displayed, despite no longer being present in the QR.history.
Expected Behavior
The QR.replaceLast('/new-path') function should produce the same result as the following sequence:
CopyQR.back();
QR.to('/new-path');

Let me know if you need more informations

**Comment by offline-first** [comment]
The same issue is with this method `QR.replace("/any-path", "/new-path")`

**Comment by offline-first** [comment]
I could not reproduce the bug in a test project. I am therefore closing the issue
