### ISSUE TITLE
Problem when returning to home page

### ISSUE THREAD

**Issue by huynhthehainam** [SchabanBo/qlevar_router#16]
When I'm at bellow page http://localhost:61817/#/nested/child-1:
![image](https://user-images.githubusercontent.com/48429857/113404968-3ca8a580-93d3-11eb-8558-82fb3ff9e8be.png)
Then I go to this url: http://localhost:61817/#/
It show the home page but the url is http://localhost:61817/#/nested/child:
![image](https://user-images.githubusercontent.com/48429857/113405132-81344100-93d3-11eb-8343-9c9a39c9c9ac.png)

**Comment by SchabanBo** [comment]
I forget to remove it from the history, so it will show it as the last page.
I fixed it in 1.1.2
Thanks for opening the issue 👍
