### ISSUE TITLE
Basic Question

### ISSUE THREAD

**Issue by bobwiller** [SchabanBo/qlevar_router#18]
Sorry if this is a basic question, but how do you navigate to a page/widget that takes a set of parameters (not URL params, but constructor params)?  For example, we have a page/widget that has a constructor like:

class MyNextScreen extends StatefulWidget {
  final Person employee;

  const MyNextScreen (
      {Key key, @required this.employee})
      : super(key: key);
  @override
  _MyNextScreen State createState() => _MyNextScreen State();
}

How do I navigate to `MyNextScreen(employee: newEmployee)` ?

All the examples show navigation happening to screens w/o parameters.  I recognize I can pass Strings or ints via web-based parameters (e.g. https://myscreen?param1=) but how do you pass objects around while navigating?

Or am I thinking about this all wrong?
Thanks,
Bob

**Comment by bobwiller** [comment]
Just as a quick follow-up, I am using the Bloc pattern, and in my Bloc I have tried this:

`QR.navigator.pushName('My Next Screen', params:{'employee': event.staff});`

And in the `MyNextScreen` I have tried "catching" that param with:
`var employee = QR.params['employee'];`

But what I wind up with is `employee` is equal to "Instance of `Employee`"

**Comment by SchabanBo** [comment]
Hi @bobwiller 
Please don't be, any question is welcome.

in the route abroach you need always to pass the parameter with the route. so if the user calls the route from the browser the page could be created in the right way.
but of course, that doesn't mean you can't pass it without the route. but you need to use `QR.params` so you could pass your object from the old page to the new one.
you could do so in two ways:

- pass it directly to the page

```dart
// From old page
QR.params.ensureExist('person', initValue: person, keepAlive: true); // set keepAlive to true so it doesn't get deleted
QR.toName('My Next Screen');

// in the new page
class MyNextScreen extends StatefulWidget {

final Person employee = QR.params['person'].valueAs<Person>();

const MyNextScreen ({Key key}): super(key: key);
@override
_MyNextScreen State createState() => _MyNextScreen State();
}

// then anywhere just set keepAlive to false so it would be cleaned up (if you want to, it could be you need it later in other pages :) )
QR.params['person'].keepAlive = false;

```

- or pass it to the constructor

```dart
// From old page
QR.params.ensureExist('person', initValue: person, keepAlive: true);
QR.toName('My Next Screen');

// in the route definition
QRoute(path: '/person', builder: (){
    final person = QR.params['person'].valueAs<Person>();
    QR.params['person'].keepAlive = false; // same thing
    return MyNextScreen(employee: person);
})
```

for receiving a param, the `QR.params[]` returns an object of type `QParam` if you want to get to your object use `QR.params[].value`. but here you will get an object of type `Object` so you can use `QR.params[].valueAs<Employee>()` to get your `Employee` object

**Comment by bobwiller** [comment]
Thanks for the feedback.  

Look like `QR.params.ensureExist' will only accept a `String` for `initValue` ?  So passing the object to the new route is still an open  question.

**Comment by SchabanBo** [comment]
Oh, it looks like I forget to change it to `Object`, I will do so in the next update.
for now, as workaround, you can do 

```dart
QR.params['person'] = person;
QR.params['person'].keepAlive = true;
```

**Comment by bambinoua** [comment]
Am I right if your package does not support navigation to pages (widgets) which contains with parameters? I.e. it is required to change the code from this:
```dart
class SomePage extends ... {
  SomePage({this.id});
  final int id;
}
```
to this:
```dart
class SomePage extends ... {
  SomePage();
  
  Widget build(...) {
     final id = QR.params['id'];
     ...
  }
}
```

**Comment by SchabanBo** [comment]
I understand that could be at the start a little annoying, but this the problem from the web/Deep-linking abroach.

When you use this abroach (URL) you are giving the possibility so the user can open any page in your app from anywhere through the URL. So you need to configure your pages so they could be open from anywhere.

let's take your example have the URL `/some-page`

```dart
class SomePage extends ... {
  SomePage({this.id});
  final int id;
  
  Widget build(...) {
    return FutureBuilder(...);
  }
}
```

and let's say we are in `/one-page` and from there the user clicks a button and we call `SomePage` page and we give it the id when we call it `SomePage(id:5)` (the way you want).
and now the user for some reason (redirected from another page) write in the browser address bar `/some-page`!!. there is no way to open it because the is no id. so you need to define the page as `/some-page/5` or `/some-page?id=5` so the page could be open from the URL. That is why we need to use the QR.params

now if you don't want to change the definition for your `some-page` you could do so. but you need to get the id from QR.params like this when you define the route

```dart
QRoute(path: '/some-page', builder: (){
    final id = QR.params['id'].asInt;
    return SomePage(id: id);
})
```
