### ISSUE TITLE
Non-used confused parameter in QRouterDelegate

### ISSUE THREAD

**Issue by bambinoua** [SchabanBo/qlevar_router#20]
I noticed the parameter `notFoundPage` in `QRouterDelegate` which is not used. And this is confusing a little as I tried to set my value for this parameter and got nothing. Is it required for new functionality or is it forgotten to remove?

**Comment by SchabanBo** [comment]
you are right. that is from old code and I forgot to remove it. Thanks for the hit.
I will remove it in the next release

**Comment by SchabanBo** [comment]
Fixed in 1.4.0
