### ISSUE TITLE
Page Transition Example

### ISSUE THREAD

**Issue by rohitranjan1991** [SchabanBo/qlevar_router#22]
Hi, Thanks for the great navigation package. I am struggling with implementing fade Transition for the routes. Can you point me to any example for the same or provide one example here.

**Comment by SchabanBo** [comment]
Hi @rohitranjan1991 ,
I glad you liked it. I will add a new page type `QFadePage` that will perform a Fade Transition.
if you want you can use `QCustomPage` for now to do so
```dart
  QRoute(
      path: '/child-4',
      pageType: QCustomPage(
          transitionsBuilder: (c, a, ra, child) => FadeTransition(
                opacity:
                    CurvedAnimation(parent: a, curve: Curves.easeIn)
                        .drive(Tween<double>(end: 1, begin: 0)),
                child: child,
              )),
      builder: () => TextPage('Hi child 4')),
]),
```

**Comment by SchabanBo** [comment]
you can go to [here](https://qlevar-router.netlify.app/#/) and then go to `params/:id` and you will get fade Transition  (if not, try to clear the browser cash )
and you can now [mix the Transition](https://github.com/SchabanBo/qlevar_router#mix-it-up) and set [App Page Transition](https://github.com/SchabanBo/qlevar_router#app-page-transition) App Page Transition
