### ISSUE TITLE
QCupertinoPage has shadows

### ISSUE THREAD

**Issue by rohitranjan1991** [SchabanBo/qlevar_router#23]
After a lot of debugging, I found that the QCupertinoPage has some sort of shadow to its boundaries. Is there any option of removing them?

**Comment by SchabanBo** [comment]
I don't think so, because at the end I am just using `CupertinoRouteTransitionMixin` which is from flutter

**Comment by rohitranjan1991** [comment]
If you see the below image, the DashboardScreen is Loaded from "this.widget.router" and if u see the inspection window, you will find _CupertinoEdgeShadowDecoration in the above tree. I think _CupertinoEdgeShadowDecoration is giving the shadow the dashboard pane.

Shadow Dashboard (Left Side of Dashboard Section)
![image](https://user-images.githubusercontent.com/4726622/119123758-874ab380-ba4d-11eb-9b66-73ec4fd56452.png)

![image](https://user-images.githubusercontent.com/4726622/119123595-566a7e80-ba4d-11eb-8e67-e94ab69e9b9b.png)

**Comment by SchabanBo** [comment]
I think you are working on a mac. and in this case, the QPlatefromPage (The default one if you didn't assign another type) will give QCupertinoPage which has a shadow.
if you assign another pageType the QPlatfromPage will be overridden and the assigned type will be used.
you can change the type for all pages by setting `QR.settings.pagesType` to the type you want to be used.

**Comment by rohitranjan1991** [comment]
Is there a away to use the QCupertino Page and get rid of the shadow ??

**Comment by SchabanBo** [comment]
No, because this is not configured from the package.
