### ISSUE TITLE
Mobile App : onBackbutton Pressed Navigate to previous route

### ISSUE THREAD

**Issue by AjayOrx** [SchabanBo/qlevar_router#25]
Hii @SchabanBo ,

I have 3 pages (/signup), (/login) and (/user/dashboard), once I signedUp and login
In the mobile app, when I pressed back button it navigates to login Page then again I pressed back button it navigates to /signup Page 
Any Solution to Close/exit the app if the user clicks back button from Dashboard?

**Comment by SchabanBo** [comment]
Hi @AjayOrx 
did you tried after login to navigate using `QR.navigator.replaceAll('/user/dashboard');`.
This will remove the signup page and login page from the stack. and should give you what you want :)
