### ISSUE TITLE
Double "//" appears for Splash Screen

### ISSUE THREAD

**Issue by rohitranjan1991** [SchabanBo/qlevar_router#26]
I get "localhost:51273/#//" for the Splash screen for the below configuration. 

class AppRoutes {
  List<QRoute> routes() => [
    QRoute.withChild(name:"app", path: "/", initRoute: "", builderChild: (r)=> EmptyBaseScreen(r),children: [
      QRoute(name: 'SplashScreen', path: '', builder: () => SplashScreen()),
      PreLoginRoutes().routes(),
      PostLoginRoutes().routes(),
    ])
      ];
}

Expected:

"/" -> SplashScreen

**Comment by SchabanBo** [comment]
You are right, I didn't consider this case.
I will fix this in the next version. Thanks.
