### ISSUE TITLE
Need Page to be recreated every time we route to it

### ISSUE THREAD

**Issue by rohitranjan1991** [SchabanBo/qlevar_router#27]
I have a scenario where i need the page to be recreated to every time i navigate to that page. 

The scenario is like this:
   Let's say I have a page A which calls an API to fetch some information and display it on the page. This API call depends on a certain API header with is set by Page B.  Now, let's assume my current header has the value "Value1". If I follow the below steps:
- navigate to Page A 
- Page A loads the data with header value "Value1"
- I navigate to Page B and change the header Value to "Value2"
- navigate back to page A with QR.toName or QR.to
- **Page A needs to refresh and reload the data with the header "Value 2" and not maintain its already fetched data (the existing state)**

If I could tell it somehow in QR.toName or QR.to functions to call the builder function again instead of returning the existing state, that would be great.

Can you please help me achieve this scenario? (I need this in my current project.)

**Comment by SchabanBo** [comment]
Page A does not rebuild because it is already in the stack.
Try when navigating to page B to remove page A from the stack, so when go back to page A it will be rebuilt.
you can use `QR.navigator.replaceAll('/page-b')` and then when you go back to page A `QR.to('/page-a')`

**Comment by rohitranjan1991** [comment]
Just curious, Would the replaceAll not replace all the other pages in the stack?

**Comment by SchabanBo** [comment]
yes, it would replace them all. I have implemented `replace` and `replaceName` so you can replace just one page. but this is still in develop branches. will be in the next release.
