### ISSUE TITLE
Any Example for nested QRoute.withChild

### ISSUE THREAD

**Issue by rohitranjan1991** [SchabanBo/qlevar_router#28]
Hi, Can you please provide me an example for nested QRoute.withChild i.e. "QRoute.withChild " inside another "QRoute.withChild". Thanks :-)

**Comment by SchabanBo** [comment]
Hi @rohitranjan1991 ,
See this [example](https://github.com/SchabanBo/qr_samples/blob/main/lib/special_cases/nested_in_nested.dart)
