### ISSUE TITLE
Top level path with same path prefix will lead to 'Page Not Found'

### ISSUE THREAD

**Issue by rockingdice** [SchabanBo/qlevar_router#3]
So after issue #2, I'd like to try another solution that makes all routes to the top.
The routes look like:
```
class AppRoutes {
  final routes = <QRouteBase>[
    QRoute(
        path: '/main/apps',
        page: (child) => PageMain(child: PageOther(),)),
    QRoute(
        path: '/main/home',
        page: (child) => PageMain(child: PageOther(),)),
    QRoute(
        path: '/main/app/:id',
        page: (child) => PageMain(child: PageOther(),)),
    QRoute(
        path: '/main/app/edit/:id',
        page: (child) => PageMain(child: PageOther(),)),
    QRoute(
        path: '/login',
        page: (child) => PageMain(child: PageOther(),)),
    QRoute(
        path: '/404',
        page: (child) => PageMain(child: PageOther(),)),
  ];
}
```
But only checked path could be found:
- [x] /main/apps
- [ ] /main/home
- [ ] /main/app/:id
- [ ] /main/app/edit/:id
- [x] /login
- [x] /404

So my quick guess is the same prefix ```/main``` lead to this issue.

I'm expecting the path could match to its page if not using nested router. So I thought this behavior is not correct.

I made a repro project for you to test:
https://github.com/rockingdice/qr_issue_repro

**Comment by SchabanBo** [comment]
actually i didn't consider this use case for the routes. when you defines the routes like this the routes tree will be 
-main
  -app
- main
  -home
- main
  -app
    -:id 
so when call main/home route the tree will return only the first main route(that contains the app route) and will search in it for home and will not find it.
if you want to use it now you have to wrap all paths that contains main in one main parent and define them as chidlren
and will fix this one and try to group them correctly
thanks for pointing this use case

**Comment by rockingdice** [comment]
I think the URL path is just a 'key' to the destination page, no matter what the key is. 

I've tried to make them children of the main route, but it leads to #2 issue, in which the parent widgets won't get updated.
I can find a way to deal with the issue as you said, it's okay.

**Comment by rockingdice** [comment]
A minor bug from v0.3.4:
```
    for (var i = 1; i < newRoute.length; i++) {
      childMatch.childMatch =
          MatchRoute.fromTree(routes: searchIn, path: newRoute[i]);
      if (!childMatch.childMatch.found) return _notFound(path);
      searchIn = childMatch.childMatch.route.children;
      childMatch = childMatch.childMatch;
    }
```
if (!**childMatch.childMatch**.found) return _notFound(path); 
childMatch.childMatch could be null, so it will raise an exception when there's no route found.

**Comment by rockingdice** [comment]
And a minor bug about QRCustomPage.
I want to use custom transition animation, but I found the inner pages don't use my transition builder:
```
     var newRoute = route.copyWith(path: pathSegments.last);
        for (var i = pathSegments.length - 2; i >= 0; i--) {
          newRoute = QRoute(
              path: pathSegments[i],
              page: (c) => c.childRouter,
              children: [newRoute]);
        }
```
should add param:
```
pageType: route.pageType,
```

And
```
  QCustomPage _getCustomPage() {
    final page = pageType as QRCustomPage;
    return QCustomPage(
        name: match.route.name,
        child: match.route.page(childRoute),
        maintainState: pageType.maintainState,
        fullscreenDialog: pageType.fullscreenDialog,
        restorationId: pageType.restorationId,
        key: key,
        matchKey: match.key,
        barrierColor: page.barrierColor,
        barrierDismissible: page.barrierDismissible,
        barrierLabel: page.barrierLabel,
        opaque: page.opaque,
        reverseTransitionDuration: page.reverseTransitionDurationmilliseconds,
        transitionDuration: page.transitionDurationmilliseconds,
        transitionsBuilder: _buildTransaction);
``` 
should change the transitionBuilder to use user defined one if available:
```
        transitionsBuilder: page.transitionsBuilder ?? _buildTransaction
```

**Comment by rockingdice** [comment]
I made a PR to solve the custom transition issue:
https://github.com/SchabanBo/qlevar_router/pull/4

**Comment by rockingdice** [comment]
Another issue about not found route:
I declare the app routes like this:
```
class AppRoutes {
  static QRCustomPage customPage =
      QRCustomPage(transitionsBuilder: (ctx, animation, secondary, child) {
    return FadeTransition(
      opacity: animation,
      child: child,
    );
  });

  static QRoute makeRoute(
      {String? path, QRoutePage? page, List<QRouteBase>? children}) {
    return QRoute(
        path: path, page: page, children: children, pageType: customPage);
  }

  static List<QRouteBase> initRoutes() {
    final routes = <QRouteBase>[
      makeRoute(
          path: '/main',
          page: (child) => PageMain(routeChild: child),
          children: [
            makeRoute(path: '/apps', page: (child) => PageAppManage()),
            makeRoute(path: '/home', page: (child) => PageHome()),
            makeRoute(path: '/app/:id', page: (child) => PageAppDashboard()),
            makeRoute(path: '/app-edit/:id', page: (child) => PageAppEdit()),
            makeRoute(path: '/app-cfg/:id', page: (child) => PageAppConfig()),
            makeRoute(path: '/app-img/:id', page: (child) => PageAppImage()),
            makeRoute(path: '/app-op/:id', page: (child) => PageAppEdit()),
          ]),
      makeRoute(path: '/login', page: (childRouter) => PageLogin()),
      makeRoute(path: '/404', page: (childRouter) => Placeholder())
    ];
    return routes;
  }
}
``` 

From PageMain I tried to navigate to '/main/app/1', but the router tells me the page is not found (with a null exception).
I can navigate to '/main/app/1' within the nested page like PageAppManage.

**Comment by SchabanBo** [comment]
> From PageMain I tried to navigate to '/main/app/1', but the router tells me the page is not found (with a null exception).
> I can navigate to '/main/app/1' within the nested page like PageAppManage.

I could not see the problem here, it works as expected

https://github.com/SchabanBo/qlevar_router_issues/blob/master/issue_3/lib/main.dart

**Comment by rockingdice** [comment]
@SchabanBo Oh! I just realized the path is not right:
```
Qlevar-Route: Navigate to /main/app/1
Qlevar-Route: Update Page app
Qlevar-Route: Update Page /main
...
Qlevar-Route: Navigate to /main/app/1/
Qlevar-Route: Update Page Root
```
The path with a slash after 1 cannot be found, but without the slash, it's working.
Maybe a parser problem?

**Comment by SchabanBo** [comment]
that is happed because if you try this
```dart
 final s = Uri.parse('/main/app/1/');
  print(s.pathSegments.length);
```
you will get 4 segments and the last one will be empty 
and the router in this case will look for the 4th child (which doesn't exist)

**Comment by rockingdice** [comment]
OK, I got it. So a '/' child route under the ':id' should work.

**Comment by SchabanBo** [comment]
yes.
but I think I should consider this in the package. if the last segment is empty just skip it.
So no need to add the `/` child for every route

**Comment by SchabanBo** [comment]
So, this should not be a problem anymore in 0.3.5 
See [Test](https://github.com/SchabanBo/qlevar_router/blob/master/test/tree_build_test.dart)

**Comment by rockingdice** [comment]
Thanks! I'll try it out.
