### ISSUE TITLE
Trying to build a tab nested navigation

### ISSUE THREAD

**Issue by cto-leaps** [SchabanBo/qlevar_router#30]
Hi and thank you for this great package.
My goal is to have an app with 4 bottom tabs that each keep their own separate navigator stack.

Right now, following your docs, I have set up the home page as follows 
```
final appRoutes = [
  QRoute.withChild(
      path: '/home',
      pageType: QFadePage(
        transitionDurationmilliseconds: 10,
      ),
      initRoute: '/feed',
      builderChild: (child) => HomeScreen(router: child),
      children: [
        QRoute(name: mainTabs[0], path: '/feed', builder: () => FeedScreen()),
        QRoute(
            name: mainTabs[1],
            path: '/workouts',
            builder: () => WorkoutsScreen()),
        QRoute(name: mainTabs[2], path: '/teams', builder: () => TeamsScreen()),
        QRoute(
            name: mainTabs[3],
            path: '/athletes',
            builder: () => ProfileScreen()),
      ]),
```

and have it working with some caveats:
When I tap one of my tabs, the corresponding screen is shown accordingly but I have the possibility to swipe right to go back to the previous one, which is not the expected behavior for tabs. Furthermore, swiping back doesn't update the bottomtapbar selected index.

So I tried to replace
`QR.toName(mainTabs[index]);`
by 
`QR.navigator.replaceAllWithName(mainTabs[index]);`
in my onTap, which makes it "better" in terms of behavior, but I am not sure if it's the best option.

And, I don't know if this will allow me to maintain the state of each tab separately as my app will end up having

- Feed
- - Notifications
- Workouts
- - Workout id#
- Teams
- - Team Id#
- - - Members
- - - - Member ID#
- - - Team Settings
- Athletes
- - Athlete id#
- - Settings

How would you go about setting this up?

Thanks very much for your precious help on this!

**Comment by cto-leaps** [comment]
One thing I forgot is I am setting up all this as I will need deep linking support to navigate straight to /teams/team/1234/members for instance...

**Comment by SchabanBo** [comment]
Hi @cto-leaps ,
I am glad you liked it.
The `swipe right to go back ` is an IOS behaver. to use this you need to set the page type to `QCupertinoPage`.
you can do something like

```dart
QR.settings.pagesType = QCupertinoPage();
````

to tell all pages to use this page type. or set it just for the pages that you want to use this behaver

```dart
 QRoute(
    pageType: QCupertinoPage(), // here
    name: tabs[0],
    path: '/',
    builder: () => Tab('Home', Colors.blueGrey.shade900)),
````

and would recommend using `QR.toName(mainTabs[index]);` so the pages can keep their state and not get removed from the stack.

**Comment by cto-leaps** [comment]
Hello @SchabanBo and thanks for your reply.
You misunderstood me though.
I **do not want** this behavior but I am getting it on the Tabs when I use the QR.toName function.

So is there a way to NOT have this when using tabs?

**Comment by SchabanBo** [comment]
In this case, you can try
https://stackoverflow.com/a/49162131
Just wrap you tap widget with WillPopScope and this should do the trick. 
I try it and it worked fine.
