### ISSUE TITLE
1.4.4 breaks web application

### ISSUE THREAD

**Issue by bobwiller** [SchabanBo/qlevar_router#32]
I am struggling to figure out what might cause a breaking change in 1.4.4 for my project when running as a website.  1.4.3 (and previous versions) all run fine.  Moving to 1.4.4, the web app launches, I see my initial route but the moment I call `QR.navigator.replaceAll('/login');` it crashes with the following stack trace:

Stack Trace:
`STACK TRACE
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 236:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 337:5             last]
packages/qlevar_router/src/controllers/pages_controller.dart 30:26                                                         removeLast
packages/qlevar_router/src/controllers/pages_controller.dart 61:7                                                          removeAll
packages/qlevar_router/src/controllers/qrouter_controller.dart 167:22                                                      replaceAll
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5            _async
packages/qlevar_router/src/controllers/qrouter_controller.dart 165:26                                                      replaceAll
packages/kiosk/bloc/application/application_cubit.dart 82:20                                                               initializeApp
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 45:50            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1362:47                                          _rootRunUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1265:19                                          runUnary
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 155:18                                    handleValue
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 707:44                                    handleValueCallback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 736:13                                    _propagateToListeners
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 542:5                                     [_completeWithValue]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 580:7                                     <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1354:13                                          _rootRun
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1258:19                                          run
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1162:7                                           runGuarded
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1202:23                                          callback
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11                              _microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5                               _startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15           <fn>
`

**Comment by SchabanBo** [comment]
Can you add some code to reproduce the problem?
I tried this code and it worked fine.
```dart
import 'package:flutter/material.dart';
import 'package:qlevar_router/qlevar_router.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static bool isAuthed = false;
  final routes = [
    QRoute(path: '/init', builder: () => LandingPage()),
    QRoute(path: '/login', builder: () => LoginScreen()),
  ];

  @override
  Widget build(BuildContext context) => MaterialApp.router(
        routeInformationParser: QRouteInformationParser(),
        routerDelegate: QRouterDelegate(routes, initPath: '/init'),
        theme: ThemeData.dark(),
      );
}

class LoginScreen extends StatefulWidget {
  @override
  _LoginScreenState createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  @override
  Widget build(BuildContext context) => Scaffold(
        appBar: AppBar(
          backwardsCompatibility: false,
          title: Text('Login'),
          centerTitle: true,
        ),
        body: Center(
          child: TextButton(
              onPressed: () => QR.navigator.replaceAll('/init'),
              child: Text('LandingPage')),
        ),
      );
}

class LandingPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) => Scaffold(
        body: FutureBuilder<bool>(
            future: Future.delayed(Duration(seconds: 2), () => true),
            builder: (c, s) {
              if (s.hasData) {
                QR.navigator.replaceAll('/login');
                return Container();
              }
              return Center(
                  child: Text(
                'Wellcome To my Sample',
                style: TextStyle(fontSize: 25, color: Colors.amber),
              ));
            }),
      );
}

```

**Comment by bobwiller** [comment]
@SchabanBo i will work on it next week - i have a deadline i am working on, but moving to 1.4.3 has saved me atm!

**Comment by SchabanBo** [comment]
@bobwiller 
Does it break on 1.5.1?
