### ISSUE TITLE
I feel like I'm doing this wrong for nested routing

### ISSUE THREAD

**Issue by michael-woolsey** [SchabanBo/qlevar_router#39]
Hello again,

I'm trying to get my routing to work with the url ids, yet it feels like I'm doing something wrong because of the way I have to transition to the children pages.

Rotues
```
    QRoute(
      path: '/testKit/results/:resultId',
      builder: () => Screen1(resultId: findParameter<String>('resultId')),
      children: [
        QRoute(
          path: 'stuff/:stuffId',
          builder: () => Screen2(stuffId: findParameter<String>('stuffId')),
        ),
      ],
    ),
```

Now to get to the test kit route I do a `await QR.to('/testKit/results/be11146a-18a1-4c46-bf6b-d76aa16b5546');` and this seems to work great.

Then I try to go to the `stuff` child screen of the `testKit` screen, but if I do a `await QR.to('stuff/1234');` then I get an error of `[stuff] is not child of Key: [-1](Root)`.  I thought a relative path should work under this circumstance.

To get this to work I had to do a `await QR.to('${QR.currentPath}/stuff/1234');` and now it works.

This feels wrong though, am I doing something wrong or is this the intended way to access children routes?

Thank you,
Michael

**Comment by SchabanBo** [comment]
Hallo @michael-woolsey,
QR.to always take a full path. because it could be called from anywhere in the app. and it uses the root navigator.
The relative path could work only when you use a child navigator `QR.navigatorOf`.

**Comment by michael-woolsey** [comment]
Okay, thank you @SchabanBo. :)
