### ISSUE TITLE
nested routes with similar path bug

### ISSUE THREAD

**Issue by Yusuf007R** [SchabanBo/qlevar_router#45]
Hello, I have been testing this library lately and everything looks amazing, except for this bug that I just found. Well I'm not sure if this is a bug or an expected behavior.
basically if you have nested routes like this.
```
      QRoute.withChild(
        path: '/home',
        initRoute: '/grid',
        builderChild: (child) => PostRouteWrapper(
          child: child,
        ),
        children: [
          QRoute(
            path: '/grid',
            builder: () => const PostScreen(),
          ),
          QRoute(
            path: '/grid/:index',
            builder: () => const PostDetailScreen(),
          )
        ],
      );
```
If you try to navigate to `/grid/index` (of course with full path so like this `/home/grid/2`). It breaks and throw this error.

```
I/flutter (12458): QR: Finding Match for /home/grid/2 under root
E/flutter (12458): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter (12458): #0      MatchController.match
package:qlevar_router/…/controllers/match_controller.dart:73
E/flutter (12458): <asynchronous suspension>
E/flutter (12458): #1      QRContext.toName
package:qlevar_router/src/qr.dart:138
E/flutter (12458): <asynchronous suspension>
E/flutter (12458):
```

I have try to debug this error, but I just can't I'm new to flutter and well I'm not experience enough to even know what is the exact problem.

**Comment by Yusuf007R** [comment]
I have found another bug, basically you cannot make a bottom bar of `QRoute.withChild()`, I want my bottom bar tabs to be `QRoute.withChild()` but everytime you navigate to one of the tab, you navigate to the `QRoute.withChild()` then the `QRoute.withChild()` navigate to the initRoute, but it looks like it `replace` instead of `to`, so it does not save the state, so everytime you navigate to the screen it lose the state, weirdly it does save the state of the first tab, the other 3 tabs lose their state. 

this is my `HomeRoute`

```
List<String> tabs = [
  "test1",
  "test2",
  "test3",
];

class HomeRoute {
  QRoute routes() => QRoute.withChild(
        path: '/home',
        initRoute: '/home2',
        builderChild: (router) => HomeScreen(
          router: router,
        ),
        children: [
          PostRoute().routes(tabs[0]),
          PostRoute().routes(tabs[1]),
          PostRoute().routes(tabs[2]),
        ],
      );
}
```

and this is my `PostRoute`
```
class PostRoute {
  QRoute routes(
    String name,
  ) =>
      QRoute.withChild(
        path: '/$name',
        initRoute: '/grid',
        name: name,
        builderChild: (child) => PostRouteWrapper(child: child),
        children: [
          QRoute(
            name: '$name-grid',
            path: '/grid',
            builder: () => const PostScreen(),
          ),
          QRoute(
            name: '$name-detail',
            path: '/detail/:index',
            builder: () => const PostDetailScreen(),
          )
        ],
      );
}
```

my `HomePage`


```
class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key, required this.router}) : super(key: key);
  final QRouter router;
  @override
  _HomeScreenState createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  @override
  void initState() {
    super.initState();
    widget.router.navigator.addListener(() {
      setState(() {});
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: widget.router,
      bottomNavigationBar: BottomNavigationBar(
        currentIndex:
            tabs.indexWhere((element) => element == widget.router.routeName),
        onTap: (value) => QR.toName(tabs[value]),
        items: const [
          BottomNavigationBarItem(
            icon: Icon(Icons.collections),
            label: 'posts',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.favorite),
            label: 'favorite',
          ),
          BottomNavigationBarItem(
            icon: Icon(Icons.recommend),
            label: 'recommended',
          ),
        ],
      ),
    );
  }
}
```

**Comment by SchabanBo** [comment]
# Answer

Hi @Yusuf007R,

First of all, I am very sorry for the late answer.

## for the nested routing

when the package search for a matching route it always take the first segment match is found (in the case `/grid`) which have no children so it could not find `/2` to solve this change your code to 

```dart
QRoute.withChild(
   path: 'home',
   builderChild: (r) => Nested1(r),
   children: [
     QRoute(path: '/grid', builder: () => WelcomePage(), children: [
       QRoute(
         path: '/:index',
         builder: () => WelcomePage(),
       )
     ]),
```

this should work.

## for the bottom bar

when you start the app you will be on the `test1` page then if you go to the `test2` page and return to `test1` the `test1` will save the state because it was already in the stack. but now if you go to `test2` the page will be recreated because when you navigated to `test1` back, `test2` was popped and removed.

That is happing because the `to` uses the `popUntilOrPush` so if the page was in the stack it will be popped until this page.

This is way in version `1.5.7` i added the parameter `pageAlreadyExistAction` to `QR.to`. you can set this to `BringToTop` and no page will be popped and all your pages will always save the state.

I will be happy to know if this solves your problems.
