### ISSUE TITLE
Dashboard example and sidebar navegation

### ISSUE THREAD

**Issue by Josua2012** [SchabanBo/qlevar_router#49]
Hi @SchabanBo,
First of all, thank you very much for the "dashboard" example, it works wonderfully well, however I have some doubts.
When I click on the sidebar options (Info, Orders, Items) the pages are created (**QR.to()**), but they do not replace each other,

```
class Sidebar extends StatelessWidget {
  const Sidebar({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Container(
        color: Colors.grey.shade800,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            ListTile(
              title: const Text('Info'),
              //onTap: () => QR.navigatorOf('/dashboard').replaceAll('/info'),
              onTap: () => QR.to('/dashboard/info'),
            ),
            ListTile(
              title: const Text('Orders'),
              //onTap: () => QR.navigatorOf('/dashboard').replaceAll('/orders'),
              onTap: () => QR.to('/dashboard/orders'),
            ),
            ListTile(
              title: const Text('Items'),
              //onTap: () => QR.navigatorOf('/dashboard').replaceAll('/items'),
              onTap: () => QR.to('/dashboard/items'),
            )
          ],
        ),
      );
}
```

that is, if I am on the Info page, when I click on Orders the Orders page is displayed but the info page is not disposed. This way is fine, but it can overload memory, wouldn't it be better if the pages were replaced? 
However, the navigability of the back and forward buttons should be the same whether the pages are destroyed or not.
Can this be done with qlevar_router? 

Again thank you very much for your help. 
Regards,
Jose

**Comment by SchabanBo** [comment]
Hi @Josua2012 ,
I am glad you found what you need.
The way that `QR.to` is working is `PushOrPupUntil` if you want to replace the pages when navigating to a new one just use 
[this](https://github.com/SchabanBo/qr_samples/blob/44d6268cc2eeff32e263bf4fd6c43e25f2e00dd5/lib/common_cases/dashboard.dart#L135) instead of QR.to.
this will replace the pages as you wish

**Comment by Josua2012** [comment]
Wonderful, I hadn't realized this other possibility. You are a crack, you have everything in mind.  :)

I have also observed that if you put a transition animation between the pages, the transition looks different and with different speed when the page is changed or when the backbutton is clicked. 

```
    QRoute.withChild(
        path: '/dashboard',
        builderChild: (c) => Dashboard(c),
        initRoute: '/info', // Set the init route for this router
        middleware: [
          // Set Auth middleware to redirect user when is not authed
          QMiddlewareBuilder(
              redirectGuardFunc: (s) async => isAuthed ? null : '/login'),
        ],
        children: [
          QRoute(
              path: '/info',
              pageType: const QFadePage(
                transitionDurationmilliseconds: 1000,
              ),
              builder: () => DashboardChild('Info', Colors.blueGrey.shade900)),
          QRoute(
              path: '/orders',
              pageType: const QFadePage(
                transitionDurationmilliseconds: 1000,
              ),
              builder: () =>
                  DashboardChild('Orders', Colors.blueGrey.shade700)),
          QRoute(
              path: '/items',
              pageType: const QFadePage(
                transitionDurationmilliseconds: 1000,
              ),
              builder: () => DashboardChild('Items', Colors.blueGrey.shade500)),
        ]),
  ];
```
Thanks.
