### ISSUE TITLE
[Feature Request] Add onWillPop callback before navigating to other routes

### ISSUE THREAD

**Issue by rockingdice** [SchabanBo/qlevar_router#5]
The scenario I want to implement is a form for data modification, if a user wants to change to other pages before submitting any contents, he will get a warning dialog. After the confirmation, the navigator continues the routing or cancels the action.

Don't know if that's possible. I have only used navigator 1.0 on the mobile platform and usually, I'll use a WillPopScope widget for handling the back button event.

I tried to put WillPopScope on the page, but it's not working when I'm navigating to other routes.

**Comment by SchabanBo** [comment]
@rockingdice WillPopScope will not work because I don't call in any place in my code `maybePop()`.
But I think I can do something similar as a callBack like `QRouteChild.canChildPop` and it takes, as a result, a Future<bool>.
It would be great if you could provide me with an example code for your case.

**Comment by rockingdice** [comment]
I think a callback is enough for this case. But any navigation that will change the URL, like backward/forward action from the web browser, back-button event on Android, or ```QR.to()```,  should always check it. 

If navigation is going to happen, the callback will be fired, then in the callback, I'll show a warning dialog, then the user will choose to continue or stop the navigation. Before the user makes a choice, the navigation will be suspended.

It's like somewhat a middleware or a guard, to handle the process of navigation.

Some websites will pause your 'Leaving' action and prompt a warning to you to choose to save the progress or quit without saving, it is what I want to achieve.

**Comment by SchabanBo** [comment]
If you navigate to [here](https://routerexample.qlevar.de/#/home/test/can-child-navigate) you can set if the child is allowed to navigate or not.
The `QRouteChild.canChildNavigatet` will be called with
- Browser Button (Back or forward) pressed.
- Browser URL changed
- Device back button pressed
- QR.to, QR.toName, or QR.back called

maybe in the future, I will give from which source is this callback called.
please note that the callback will be called only when a child for this route is called.

**Comment by rockingdice** [comment]
@SchabanBo seems the example is not working anymore, could you please check the link again?

**Comment by SchabanBo** [comment]
@rockingdice you need to clear your browser cash (do ctr+F5 on the website)

**Comment by rockingdice** [comment]
@SchabanBo Oh my fault! I tested it and it's working, nice!
