### ISSUE TITLE
Contextual help

### ISSUE THREAD

**Issue by Josua2012** [SchabanBo/qlevar_router#50]
Hi @SchabanBo,
It would be very nice if the contextual help showed some explanation of how a class, function or parameter works.
![2021-11-28_21-14-17](https://user-images.githubusercontent.com/1523607/143784462-a46bf351-7e1a-42ca-a7fb-301957f1cbdb.jpg)

![2021-11-28_21-15-17](https://user-images.githubusercontent.com/1523607/143784466-dfe04849-f26a-41bf-84d5-84274fb052c8.jpg)

Thanks.

**Comment by SchabanBo** [comment]
Added in V1.5.8
