### ISSUE TITLE
Dashboard example and check current page

### ISSUE THREAD

**Issue by Josua2012** [SchabanBo/qlevar_router#51]
Hi @SchabanBo,
When I am in one of the dashboard pages (for example, orders), how could the corresponding option be illuminated in the sidebar?
Also, if I am in one of the pages (for example, orders) and I click on the same option I would not want the page to be recreated again.
Can you do all this with qlevar_router? 
Thanks for your help.
Regards,
Jose

**Comment by SchabanBo** [comment]
Hi @Josua2012 ,


> When I am in one of the dashboard pages (for example, orders), how could the corresponding option be illuminated in the sidebar?

to do so you could check `QR.currentPath` or `QR.navigator.currentRoute` to get the current active QRoute.

> Also, if I am in one of the pages (for example, orders) and I click on the same option I would not want the page to be recreated again.

For this, I have added in V1.5.8 `QR.QR.IsSamePath` and `QR.IsSamePath` to check if a route is currently active. 
Otherwise `QR.to` and `QR.toName` have `ignoreSamePath` that ignore the route if it is the same as the current.

Happy to help.

**Comment by Josua2012** [comment]
> For this, I have added in V1.5.8 QR.QR.IsSamePath and QR.IsSamePath to check if a route is currently active.
> Otherwise QR.to and QR.toName have ignoreSamePath that ignore the route if it is the same as the current.

I have tried to use the new features (`QR.QR.IsSamePath` and `QR.IsSamePath`) that you have added in the new version 1.5.8, but they are not recognized in my project.
Also, how `ignoreSamePath` can be used with: 
`QR.navigatorOf('/dashboard').replaceAll('/info');`
Again, thanks for your help. 👍

**Comment by SchabanBo** [comment]
Sorry the function names are `QR.isCurrentPath` and `QR.isCurrentName` i changed them brfore releasing.
`ignoreSamePath` is used just with `QR.to` and `QR.toName`
