### ISSUE TITLE
Hot reload problem

### ISSUE THREAD

**Issue by Josua2012** [SchabanBo/qlevar_router#53]
Hi @SchabanBo,
In the example of the dashboard, if I am, for example in "http://localhost:64452/#/dashboard/info", when hot reload is done it does not remain on the same page, instead the page http://localhost: 64452/#/login is shown
In other router plugins the hot reload stays on the same page. 
Is this a problem with your plugin? 
Thanks.
Regards,
Jose

**Comment by SchabanBo** [comment]
Hi @Josua2012 ,
This is a problem from flutter, there is an [issue](https://github.com/flutter/flutter/issues/53041) for it.
as work around you could do [this](https://github.com/SchabanBo/qlevar_router#web-hot-reload) for now

**Comment by Josua2012** [comment]
I have tried to do the work around you have indicated, but the hot reload continues to load the login page. 
![2021-11-30_21-18-48](https://user-images.githubusercontent.com/1523607/144122095-19351a9b-b97d-4db0-a580-ecbf7075c530.jpg)

**Comment by SchabanBo** [comment]
> I have tried to do the work around you have indicated, but the hot reload continues to load the login page.

on which platform did you try it?

**Comment by Josua2012** [comment]
> on which platform did you try it?

Chrome 96.0.4664.45
Windows 10 Pro 21H2
