### ISSUE TITLE
Customize or remove Loading blank page

### ISSUE THREAD

**Issue by henriquetroiano** [SchabanBo/qlevar_router#55]
Hi guys!
Im trying to find out how to customize the blank page with a centered "loading" at the app opening (probably the Qlevar router startup), but I couldnt found. 
I liked a lot this package.
Can you help me with that?
Thanks in advance

**Comment by SchabanBo** [comment]
Hi @henriquetroiano, 
To do so
```dart
QR.settings.initPage = // The page you want to show
```
I am glad you liked it :)
