### ISSUE TITLE
Navigator.pushReplacement, Navigator.popUntilAndPush

### ISSUE THREAD

**Issue by Stevensie95** [SchabanBo/qlevar_router#58]
First of all, really really thanks for this AMAZING package and it really save my life due to the context-less navigation for navigation 2.0. Would like to ask , is there any way to achieve effect like **Navigator.pushReplacement**, **Navigator.popUntilAndPush**, and **Navigator.popUntil** with current exists function?

**Comment by SchabanBo** [comment]
Hi @Stevensie95,

I am very glad you liked it. Thanks. 
for the navigation you cloud use :
|Navigator| QR |
|--|--|
|Navigator.pushReplacement | QR.navigator.replaceLast|
|Navigator.popUntilAndPush|QR.navigator.popUntilOrPush + QR.to|
|Navigator.popUntil|QR.navigator.popUntilOrPush|

**Comment by Stevensie95** [comment]
It's worked, thanks!
