### ISSUE TITLE
Page Results

### ISSUE THREAD

**Issue by michaelprimez** [SchabanBo/qlevar_router#59]
Hi @SchabanBo,

I am wondering how can I get results from a page. There are cases where a page is there to calculate something and return  it to the caller. I couldn't fine any example for this use case. Or did I miss something?

Thanks

**Comment by tejHackerDEV** [comment]
@michaelprimez @SchabanBo I too have the same issue, is there any solution available for this? I want to send back the result to the previous page. Like 

final result = await QR.toName(pageName);
And in the otherPage it will be
QR.back(result: anyValue);
then console.log(result) should print anyValue;
