### ISSUE TITLE
Dashboard sidebar onTap to restore page nested state

### ISSUE THREAD

**Issue by RoyGuanyu** [SchabanBo/qlevar_router#61]
Really appreciate this great package and the excellent example 💯 👍 😄 

I would like to know how this package can work in this scenario:
1. run the example in this repo
2. already login and click sidebar stores to http://localhost:57974/#/dashboard/stores
3. do some subpage, finally stay at http://localhost:57974/#/dashboard/stores/3/product/6 
4. click sidebar nav to home  http://localhost:57974/#/dashboard/home
5. nav back to stores by click sidebar, for now it would be http://localhost:57974/#/dashboard/stores

Would it be possible to nav back to http://localhost:57974/#/dashboard/stores/3/product/6 ?
in sidebar_section.dart 
 onTap: () {
              QR.to('dashboard/stores');
},

how can I easily nav to last sub page navigation ex. (dashboard/stores/xxx/xxx/xxx/xx)?

Thank you a lot for creating suck great package !!

**Comment by SchabanBo** [comment]
Hi @RoyGuanyu,
I am glad you liked it. Thanks.
Unemotionally, this is not supported yet, but this will be a good idea to implement. 
I will try to implement this when I got some time.

**Comment by NeoLee3773** [comment]
One way to achieve that would be: when you land in a page save it to a variable lastPath and provide onpressed on the back button to navigate to lastPath.

**Comment by SchabanBo** [comment]
So finally, I implemented this in V1.8.0. To achieve this now in your app, you need to do [this.](https://github.com/SchabanBo/qlevar_router/blob/master/example/lib/pages/dashboard/sidebar_section.dart#L25) Which will save the order and the state of the pages.
