### ISSUE TITLE
Android back button on root screen

### ISSUE THREAD

**Issue by vasil-comstream** [SchabanBo/qlevar_router#69]
Hello,

first of all thanks for the great package!

I have a problem on Android:
the Back button should leave the application if this is the only screen in the stack. The standard Flutter "Counter" app works as expected but qlevar_router intercepts the Back button and nothing happens.

**Comment by SchabanBo** [comment]
Hello @vasil-comstream ,
Thanks, I am glad you liked it.
This is fixed now in V1.6.1.
Thanks for reporting the issue 👍

**Comment by vasil-comstream** [comment]
Thanks! 
Officially: that was the quickest fix ever! :)

Great work!
