### ISSUE TITLE
Can I have two params in one path segment?

### ISSUE THREAD

**Issue by rockingdice** [SchabanBo/qlevar_router#7]
```/app/:id/preview/:file```
or
```/app/preview/:id/:file```
or
```/app/:id-:file```

Seems not working.  The page won't get updated.

**Comment by rockingdice** [comment]
Found out I should not put a '#' in the path, which will mess up the params.
But I found the initState of pages will fire twice sometimes, it won't happen from version 0.3.4.

**Comment by SchabanBo** [comment]
- The first and the second case are working you can test them [here](https://routerexample.qlevar.de/#/home/test/55/Max)
- In the third case, you can join them send them, and then split them. unfortunately, there is no builtin way to do this
- For the hashtag problem, I think this is from flutter [Prevent flutter web cuts off the URL path #
](https://stackoverflow.com/questions/60075992/prevent-flutter-web-cuts-off-the-url-path)
