### ISSUE TITLE
QDialog migration?

### ISSUE THREAD

**Issue by bobwiller** [SchabanBo/qlevar_router#70]
We have a lot of places where we are using QDialog via QR.show(QDialog(....)

Unfortunately QDialog was removed in 1.6.0.  What was the reason for this, and any recommendation on a migration best practice?

**Comment by bobwiller** [comment]
Thx - I can lock the version number in our pubspec for the moment until your package is done and/or we determine a direction moving forward.  Thanks for the info.

**Comment by RoyGuanyu** [comment]
Thanks for having this thread, 
if without overlay like showDialog, is there any effects for fun like QR.back()?
is there's another way to mock overlay effect in latest version? 
thanks :)

**Comment by SchabanBo** [comment]
@RoyGuanyu I didn't really understand what do you mean? Because when you use showDialog you can't close it with QR.back().

And as I said, I removed the dialog from this package, so this package can focus on the Navigation. And all other things Overlay related will be in other one.

**Comment by SchabanBo** [comment]
@bobwiller @RoyGuanyu The package for overlays is ready [Overlayment](https://pub.dev/packages/overlayment)

**Comment by RoyGuanyu** [comment]
Thank you for the reminder, @SchabanBo 
Btw, he concept of using QR.back to close the dialog is from GetX :)
