### ISSUE TITLE
Can't able to close app if root route is an Nested navigation with QRoute.withChild

### ISSUE THREAD

**Issue by manish1238** [SchabanBo/qlevar_router#72]
Hi @SchabanBo , First of all Thanks for the package.

I'm facing a serious problem which is important to be solved in this package.

You can use your example project to reproduce the issue.
Open https://qlevar-router.netlify.app/#/dashboard/home & press login, you will be landed into Dashboard page

Now if i press back button it is not closing the app even in browser if I press the default back button available in the browser it is not going back, instead it is recreating the Dashboard page again & again & we have the same problem in our production app.

Where user Login then he lands in Dashboard (using QR.navigator.replaceLastName('dashboard')) which have nested navigation with BottomNavigation & pressing default back button provided by the system, app is not getting closed instead it is creating the Dashboard page again & again.

**Comment by SchabanBo** [comment]
Hi @manish1238,
When you press back from the dashboard, this [middleware](https://github.com/SchabanBo/qlevar_router/blob/b4259c10e2cdf962cffd4c12ffa240b2bcb63ec7/example/lib/routes/app_routes.dart#L74) will run and redirect to the dashboard again because the use is Authed. If you removed this middleware and pressed back, the app will show the login page.
Can I know which version are you using? And more info about the problem in your app.

**Comment by manish1238** [comment]
Hi @SchabanBo, Thanks for the reply.

Actually we didn't have any middleware in our code we are using replaceLastName function to completely replace the last route with the current route. Check out the below repo. Clone it & run in your mobile device, once user lands on the dashboard he can't able to close the app by pressing back-button (this is the same issue that we have in our app), instead it is creating the dashboard page again & again. Also one more issue if you press on the second page option in the bottom nav, some kind of animation happens which does seem to be good in transition, so is there any way we can remove it?

https://github.com/manish1238/qlevar_test

**Comment by manish1238** [comment]
Thanks for the quick fix.
