### ISSUE TITLE
WillPopScope not working?

### ISSUE THREAD

**Issue by hiroppi401** [SchabanBo/qlevar_router#74]
qlevar_router is so great router i ever use, i just confused how to doing something before pop,
for example
1. i want clear all getx controller before pop
2. i want do some conditional pop or replace to other path

i need a guidance to achieve this, thanks before

**Comment by SchabanBo** [comment]
Hi @hiroppi401,
Thanks, I'm glad you liked it.
To do what you are looking for, you can use middleware with 'CanPop' or with 'OnExit'
See the graph [here](https://github.com/SchabanBo/qlevar_router#middleware)

**Comment by hiroppi401** [comment]
> Hi @hiroppi401, Thanks, I'm glad you liked it. To do what you are looking for, you can use middleware with 'CanPop' or with 'OnExit' Check this: ![here](https://github.com/SchabanBo/qlevar_router/blob/master/example/assets/middleware.png?raw=true) After the page is ready there and user clicks back, the `canPop` and `OnExit` methods will be called for every defined middleware on the route.

thank you sir, i'll try that
