### ISSUE TITLE
How to return result/data back to the previous page?

### ISSUE THREAD

**Issue by tejHackerDEV** [SchabanBo/qlevar_router#77]
Hi @SchabanBo I didn't find any example on how to send the result back to the previous page.

Eg:-
https://docs.flutter.dev/cookbook/navigation/returning-data

I found there is issue logged already in the repo but it doesn't have any answers & marked as close, so reopening it again. So please check on this as this is a common use-case for most of the people

**Comment by SchabanBo** [comment]
Hi @tejHackerDEV
Unfortunately that is not supported in Navigator 2 because it just updates the page stack with waiting for the page to be closed,
I will try to figure a way to achieve this. But not sure if it will work.

**Comment by tejHackerDEV** [comment]
I don't know that it is not supported by Navigator 2 but it would be great if we make any work around for that.

**Comment by SchabanBo** [comment]
You can see the example to do so [here](https://github.com/SchabanBo/qr_samples/blob/main/lib/examples/return_data.dart)
