### ISSUE TITLE
error replaceLastName

### ISSUE THREAD

**Issue by hiroppi401** [SchabanBo/qlevar_router#78]
i got error when do QR.navigator.replaceLastName
![Screenshot_2022-09-07_11-24-31](https://user-images.githubusercontent.com/48790378/188788768-9c57f806-626a-4b77-8c58-098e90bf4a43.png)
those error if use replaceLastName, when using replaceName its work fine

**Comment by SchabanBo** [comment]
Hi @hiroppi401 ,
Which version are you using?

**Comment by hiroppi401** [comment]
> 

i'm using version 1.6.3

**Comment by SchabanBo** [comment]
Could you provide an example code of the problem, I tried one, and it worked as expected!
