### ISSUE TITLE
When i move to  page from selecting sider bar menu page  not refersh 

### ISSUE THREAD

**Issue by atulproject99** [SchabanBo/qlevar_router#79]
From other menu when i click on feedback menu give this messge page not referesh

QR: Finding Match for dashboard/feedback under root
Added
Observer: popping out from /dashboard/adminusers
update

But when i click on again feedback menu then its refersh
QR: Finding Match for dashboard/feedback under root
Added
Observer: popping out from /dashboard/feedback
QR: adding Route: Key: [32](feedback), Full Path: /dashboard/feedback to the navigator with Key: [37](dashboard)
Enter in feedback
Observer: Navigating to /dashboard/feedback

i use this line for navigating and also same for other menus 

  QR.to("dashboard/${RoutesPath.feebackPage}",
            pageAlreadyExistAction: PageAlreadyExistAction.Remove);

**Comment by SchabanBo** [comment]
Hi @atulproject99 ,
Could you please provide me a sample code for the issue?

**Comment by atulproject99** [comment]
void navigateToPage(BuildContext context, int index, WidgetRef ref) async {
    switch (index) {
      case 0:
        QR.to(RoutesPath.DASHBOARD,
            ignoreSamePath: false,
            pageAlreadyExistAction: PageAlreadyExistAction.Remove);
        ref.read(titleProvider.notifier).setTitle("Dashboard");

        break;
      case 1:
        QR.to("dashboard/${RoutesPath.NEW_APP_USER}",
            ignoreSamePath: false,
            pageAlreadyExistAction: PageAlreadyExistAction.Remove);

        ref.read(titleProvider.notifier).setTitle("App Users");

        break;
      case 2:
        QR.to("dashboard/${RoutesPath.ADMIN_USERAS}",
            ignoreSamePath: false,
            pageAlreadyExistAction: PageAlreadyExistAction.Remove);
        ref.read(titleProvider.notifier).setTitle("Admin users");

        break;
      case 3:
        QR.to("dashboard/${RoutesPath.WHITE_DOMAIN}",
            ignoreSamePath: false,
            pageAlreadyExistAction: PageAlreadyExistAction.Remove);
        ref.read(titleProvider.notifier).setTitle("White-listed domains");

        break;

      case 6:
        QR.to("dashboard/${RoutesPath.NOTIFICATION}",
            ignoreSamePath: false,
            pageAlreadyExistAction: PageAlreadyExistAction.Remove);
        ref.read(titleProvider.notifier).setTitle("Notifications");
        break;
      case 7:
        QR.to("dashboard/${RoutesPath.meetTeam}",
            ignoreSamePath: false,
            pageAlreadyExistAction: PageAlreadyExistAction.Remove);
        ref.read(titleProvider.notifier).setTitle("Meet Team List");

        break;
      case 8:
        ref.read(titleProvider.notifier).setTitle("Feedback List");

        QR.toName('feedback',
            ignoreSamePath: false,
            pageAlreadyExistAction: PageAlreadyExistAction.Remove);

        break;
      case 9:
        QR.to("dashboard/${RoutesPath.CONTACT_US}",
            ignoreSamePath: false,
            pageAlreadyExistAction: PageAlreadyExistAction.Remove);
        ref.read(titleProvider.notifier).setTitle("Contact Us");

        break;

      case 11:
        showDialog(
            useRootNavigator: false,
            context: context,
            builder: (context) => CommonDialog(
                  type: 2,
                  yesCallback: () async {
                    ref.read(logoutProvider.notifier).logout(context, ref);
                    // AutoRouter.of(context).replaceAll([const LoginRoute()]);
                  },
                  noCallBack: () {
                    Navigator.of(context).pop();
                  },
                ));

        break;
    }
  }





#######################################################
I use this code for navigate to pages . pages also not remove from stack so page will not refersh.
