### ISSUE TITLE
Access context inside of middleware

### ISSUE THREAD

**Issue by theweiweiway** [SchabanBo/qlevar_router#8]
Hi @SchabanBo !

Great package, I had a quick question. For the route guard, is there a way to get the context? Please see the example below: 
   
```dart
middleware: [
  QMiddlewareBuilder(redirectGuardFunc: () async {
    // instead of relying oh AuthService, is it possible to rely on a AuthBloc? I would need
    // access context though
    return await AuthService().isLogged ? null : '/login';
  })
],
```

**Comment by SchabanBo** [comment]
Hi @theweiweiway,

I am glad you liked it.
actually, I didn't think about it or needed it before, it is a good point.
but the problem I don't have any access to any context so I can provide it, the only thing I could provide is the NavigationKey for the Navigator. I don't know if that could help, or do you have any other ideas?

**Comment by theweiweiway** [comment]
Ah I see - there's no way you could somehow get context in the `redirectGuardFunc`?

```
middleware: [
  QMiddlewareBuilder(redirectGuardFunc: (context) async {
  ... 
  })
],
```

**Comment by SchabanBo** [comment]
As long as I don't have any, no I can't.
