### ISSUE TITLE
[Feature Request] Pass data between page in arguments (don't expose them in params)

### ISSUE THREAD

**Issue by tejHackerDEV** [SchabanBo/qlevar_router#81]
Hi @SchabanBo I wanted to request for a feature in the package i.e., right now to pass the data between pages we are using params which will exposed on the address bar (in web) but lets suppose say I am passing custom objects then it is showing the runtime type of it in the url which looks ugly.

Eg:- Let suppose say if I have an  variable holding a map with custom class named Abc. Then if I pass it to the another page with the key as abc then in the url it will be rendering is ?abc=%5BInstance%20of%20%27Abc%27%5D

Same happens if I want to pass the uint8List(which is a file) between pages then in the address bar it is flooded with the complete bytes & sometimes it throws length exceeded for the url.

If I am not wrong in GetX, we have arguments concept where we can pass data using it which is a dynamic value so we can pass anything & on the other side we can get it which can't be exposed in the url query params. So if same kind of functionality is implemented then it will be great

**Comment by atulproject99** [comment]
I think @tejHackerDEV its fine so if you are working on flutter web. then it's not good way to pass any complex type of data as you mentioned. Suppose you have showing list of products just you want to showing details on next page then you just need to pass product id and in next page you hit api. for get product details so not god way to send object of model of product.So when you hitting url of details page then its working well.

**Comment by tejHackerDEV** [comment]
@atulproject99  yes it is not a good way of passing complex data as you mention in your example it is fine but lets say we want to edit a file that is being picked up from file manager. Then selecting from the fileManager we want to pass that data to the ImageEditor or FileEditor page where we want to edit it. As that page takes input of a file we need to pass them so in these kind of cases it is necessary. One way of handling these things is opening dialogs but it will become hard to maintain if we have this functionality in multiple places of app

**Comment by SchabanBo** [comment]
This could be good. Maybe something like:
```dart
QR.params.addAsHiden('file', file);
```
then you can get your data from the next page:
```dart
final file = QR.params['file']?.valueAs<File>();
```
And this parameter will not be shown in the URL. But the problem here on the web if the user refreshes the page then the data will be lost and CANNOT be restored.

**Comment by SchabanBo** [comment]
Added in 1.7.0
