### ISSUE TITLE
Previous page api  call on other page due to remain previous page in stack 

### ISSUE THREAD

**Issue by atulproject99** [SchabanBo/qlevar_router#82]
Actually i am working on a admin panel. I use this package for routing. So when i move to one page to other page then previous page api also called because the previous page not remove from stack .So please help me with the issue

**Comment by SchabanBo** [comment]
you can use replace all if you want to clean up the stack on every call, so you have only one page in the stack.
```dart
QR.navigatorOf('the name of the dashboard root').replaceAllWithName('the name of the child you want to go to')
```

**Comment by atulproject99** [comment]
@SchabanBo Thanks for help me.
