### ISSUE TITLE
Observers inside QRouterDelegate is not getting called when navigating between childs

### ISSUE THREAD

**Issue by tejHackerDEV** [SchabanBo/qlevar_router#84]
Hi @SchabanBo, I passed an custom NavigationObserver class which extends RouteObserver<ModelRoute<dynamic>> into the observers array exposed by QRouterDelegate & I override the methods didPush, didReplace, didPop methods & added a print statements inside them. Now when I navigate between child's via bottom navigation (nested navigation) the observer which I made is not getting printed. But lets suppose say if I navigate between parent child's then observer is printing details so please look into this as this is very much needed as we are using FirebaseAnalytics & wanted to track the user screens using FirebaseAnalyticsObserver

**Comment by SchabanBo** [comment]
Hi @tejHackerDEV,
That is right, at this time the observer is only assigned for the root navigator.
I will change this, so you can pass an observer for every nested navigator.

**Comment by SchabanBo** [comment]
Added in 1.7.0
