### ISSUE TITLE
I try to access a routes from url due to this api calling twice.

### ISSUE THREAD

**Issue by atulproject99** [SchabanBo/qlevar_router#87]
I try to access a routes from url i found that api calls two time on that route but i call api in init state then i don't know why its happing.Please help me  with this problem@SchabanBo 

![image](https://user-images.githubusercontent.com/71038525/195264117-0f9a1d7d-aec9-4dfd-aece-22137ed4dac1.png)

**Comment by SchabanBo** [comment]
Hi @atulproject99, I need to see some code
