### ISSUE TITLE
Error : Uncaught (in promise) TypeError: Failed to execute 'Cache' on 'addAll': Request failed

### ISSUE THREAD

**Issue by guruprakashIT** [SchabanBo/qlevar_router#9]
In my local , i am using this routing. it works fine. but when i'm going to deploy in aws, i'm getting this error. once i remove all routing coding it works in release mode. so my code was not wrong . once i include the routing code in flutter project. i getting this above error

**Comment by SchabanBo** [comment]
Could you provide some more info?
Flutter version,
qlevar_router version,
when this error appears? when you navigate to some route or the project does not run at all?

**Comment by ajaylg** [comment]
i'm also facing the same issue

Flutter 2.0.1 • channel stable • 
Tools • Dart 2.12.0
qlevar_router: ^1.1.0

while working in Localhost it's working fine. but when I deploy in AWS it shows page not found

my initial route is the same as your example Project
QRoute(name: subdomain, path: '/', builder: () => SubDomain())  

After hit URL , subDomain page comes but within a millisecond it says page not found  
Can you guide us in this issue @SchabanBo 
Thanks in advance
![issue](https://user-images.githubusercontent.com/42292816/111897559-92ca3000-8a46-11eb-8427-061af176296a.PNG)

**Comment by SchabanBo** [comment]
Sorry for the late response, but I tried to deploy to AWS (my first deployment on AWS, so it took a little bit), but the weird [It works fine](http://myqlevar.s3-website.eu-central-1.amazonaws.com/#/parent), so I could not find the problem.

But from the image you provide @ajaylg , it looks like the browser trying to navigate to the `/index.html` route which I think is not defined in the routes tree.
Could you please try adding the flowing route to your routes and try if this will works?
```dart
QRoute(path: '/index.html', builder: () => Container(), middleware: [
          QMiddlewareBuilder(redirectGuardFunc: (s) async => '/')
        ]),
```

**Comment by guruprakashIT** [comment]
@SchabanBo  now working.

i'm going to close this issue

Thank you

**Comment by ajaylg** [comment]
Hey @SchabanBo, It's Working now 
Thankzzz a lot
