### ISSUE TITLE
Nested router refreshes page

### ISSUE THREAD

**Issue by SchabanBo** [SchabanBo/qlevar_router#90]
If the initial route for nested router was `/` and this router was active and navigate to the initial route, the page will refresh.
See this [example](https://github.com/SchabanBo/qr_samples/blob/main/lib/common_cases/nav_rail.dart) 

![Oct-28-2022 12-24-07](https://user-images.githubusercontent.com/49782771/198566275-2eb099be-66bc-4bb5-ba2e-eea8f464d89a.gif)

**Comment by tejHackerDEV** [comment]
Hi @SchabanBo, can you look into #86, I added some comments. The issue should be re-opened
