### ISSUE TITLE
History Bug

### ISSUE THREAD

**Issue by nnadir35** [SchabanBo/qlevar_router#93]
Hi. I faced issue when i use the QR.history. I want to use QR.history' s output like a stack. 

For example:
profileview -> feedview -> settingsview ->favoritesview -> profileview 

and then i click browser back button

url is correct but 

QR.history entries like this:

element.path::/main/
element.path::/main/profile

Thats my routes:

```dart 
class AppRoutes {
    final routes = [
      QRoute(path: splashViewRoute, builder: () => const SplashView()),
      QRoute(path: onboardViewRoute, builder: () => const OnboardView()),
      QRoute(path: loginViewRoute, builder: () => const LoginView()),
      QRoute.withChild(
        initRoute: feedViewRoute,
        path: mainViewRoute,
        builderChild: (context) => MainView(
          qRouter: context,
        ),
        children: [
          QRoute(path: profileViewRoute, builder: () => const ProfileView()),
          QRoute(path: menuViewRoute, builder: () => FeedView()),
          QRoute(path: tablesViewRoute, builder: () => const SettingsView()),
          QRoute(path: paymentViewRoute, builder: () => const FavoritesView()),

        ],
      ),
    ];
  }
```

I want to get history like url style. How can i solve this problem ?

**Comment by SchabanBo** [comment]
Hi @nnadir35,
I am sorry for the late response. I didn't understand the problem? Do you want the history to be in URL style like `www.example.com/main/settings`?
