### ISSUE TITLE
Why its navigating different pages it should  Navigating to /home/users/userDetails?user_id=62 .Please help me this error

### ISSUE THREAD

**Issue by atulproject99** [SchabanBo/qlevar_router#94]
QR: incoming init path /home/users/userDetails?user_id=62
QR: Finding Match for /home/users/userDetails?user_id=62 under root
QR: adding Route: Key: [1](home), Full Path: /home to the navigator with Key: [-1](Root)
Observer: Navigating to /home
QR: adding Route: Key: [3](userPage), Full Path: /home/users to the navigator with Key: [10](home)
Observer: Navigating to /home/users
Observer: Navigating to /home/users/userDetails?user_id=62

**Comment by SchabanBo** [comment]
Could you please add some example code to reproduce the problem? I can't figure it out from the log.

**Comment by atulproject99** [comment]
actually the problem is the first page contains list of page that name is "users" and other page is "userdetails" So when i want to see specific user details so i click on a item of list its navigate to userdetails page but when i see console which i mentioned above finding path is fine why its not navigate directly  Navigating to /home/users/userDetails?user_id=62. ?
instead of this if first navigation home then users page then navigate userdetails page due to this mulitple api calls So how can i resolve this?
