### ISSUE TITLE
package:qlevar_router giving error _routes.isNotEmpty': is not true Giving Error on Application

### ISSUE THREAD

**Issue by anandrajak2** [SchabanBo/qlevar_router#99]
'package:qlevar_router/src/routes/qroute_children.dart': Failed assertion: line 12 pos 16: '_routes.isNotEmpty': is not true.
package:qlevar_router/…/routes/qroute_children.dart:12

**Comment by SchabanBo** [comment]
That is means you are using `QRouter.withChild` without giving any children to the route.
